//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Addresses()
        {
            this.ReqGoodTransfer = new HashSet<ReqGoodTransfer>();
            this.ReqGoodTransfer1 = new HashSet<ReqGoodTransfer>();
            this.CO01UT = new HashSet<CO01UT>();
            this.TransportAv = new HashSet<TransportAv>();
            this.TransportAv1 = new HashSet<TransportAv>();
        }
    
        public System.Guid AddressID { get; set; }
        public int Type { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string District { get; set; }
        public string HouseName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string HouseNumber { get; set; }
        public string PostCode { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string Town { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReqGoodTransfer> ReqGoodTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReqGoodTransfer> ReqGoodTransfer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO01UT> CO01UT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportAv> TransportAv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportAv> TransportAv1 { get; set; }
    }
}
