//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO01UT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO01UT()
        {
            this.ReqGoodTransfer = new HashSet<ReqGoodTransfer>();
        }
    
        public System.Guid ID { get; set; }
        public string UTEN { get; set; }
        public string TIPU { get; set; }
        public string PASS { get; set; }
        public Nullable<short> PWGG { get; set; }
        public Nullable<System.DateTime> PWSC { get; set; }
        public string NOME { get; set; }
        public string LANG { get; set; }
        public string EMAI { get; set; }
        public string TELE { get; set; }
        public string FAXN { get; set; }
        public string UFFI { get; set; }
        public string RIF1 { get; set; }
        public string RIF2 { get; set; }
        public string TELE2 { get; set; }
        public Nullable<System.Guid> ADR_ID { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReqGoodTransfer> ReqGoodTransfer { get; set; }
    }
}
