//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public partial class db_ReqGoodTransferWithAddresses
    {
        public string from_lat { get; set; }
        public string from_lng { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AddressFrom { get; set; }
        public Nullable<System.Guid> AddreessDest { get; set; }
        public Nullable<System.DateTime> DateTransportFixed { get; set; }
        public int DateTransportType { get; set; }
        public string DateTransportInfo { get; set; }
        public int RequestState { get; set; }
        public string VolRequired { get; set; }
        public string from_formatted_address { get; set; }
        public string from_location_type { get; set; }
        public string dest_formatted_address { get; set; }
        public string dest_location_type { get; set; }
        public string dest_lat { get; set; }
        public string dest_lng { get; set; }
        public string user_formatted_address { get; set; }
        public string user_location_type { get; set; }
        public string user_lat { get; set; }
        public string user_lng { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserTELE { get; set; }
        public string UserTEL2 { get; set; }
        public string UserLang { get; set; }
    }
}
