//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoCodeAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeoCodeAddress()
        {
            this.ReqGoodTransfer = new HashSet<ReqGoodTransfer>();
            this.ReqGoodTransfer1 = new HashSet<ReqGoodTransfer>();
            this.TransportAv = new HashSet<TransportAv>();
            this.TransportAv1 = new HashSet<TransportAv>();
        }
    
        public System.Guid Id { get; set; }
        public string formatted_address { get; set; }
        public string location_type { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReqGoodTransfer> ReqGoodTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReqGoodTransfer> ReqGoodTransfer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportAv> TransportAv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportAv> TransportAv1 { get; set; }
    }
}
